version: '3.7'

services:
  shopping-cart:
    image: shopping-cart:development-latest
    environment:
      NODE_ENV: development
    ports:
      - 3000:3080
  
  mongodb:
    ports:
      - 27017:27017
  
secrets:
  mongodb-username:
    file: ./secrets/mongo-username.txt

  mongodb-password:
    file: ./secrets/mongo-password.txt

volumes:
  mongodb-volume:
